services:
  db:
    image: postgres:16-alpine
    container_name: backspace_komputer_db
    restart: unless-stopped
    environment:
      # Change to match your ENV file
      POSTGRES_USER: backspace_admin
      POSTGRES_PASSWORD: rahasia123
      POSTGRES_DB: backspace_komputer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backspace_admin -d backspace_komputer"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: